#pragma once


#define UNITS_PER_BLOCK 16
#define PIXELS_PER_BLOCK 16
#define SCREEN_PIXEL_IN_PIXEL 32
#define UNITS_PER_PIXEL (UNITS_PER_BLOCK / PIXELS_PER_BLOCK)
#define UNITS_TO_PIXEL_SCALE ((float)UNITS_PER_BLOCK / (float)PIXELS_PER_BLOCK)
#define SCALING_FACTOR 2

#define TARGET_FPS 60

#define DRAW_DEBUG
